// ADVANTAGES/DISADVANTAGES LINKED LIST:
//  ADVANTAGE: THE DYNAMIC SIZE OF THE LINKED LIST CAN BE EASILY CHANGED AND INSERTING A NEW NODE IS VERY EASY.
//	DISADVANTAGE: GOING THROUGH THE LINKED LIST IS SLOW SINCE LOOKING FOR A SPECIFIC COMMAND CAN BE AT THE END AND YOU CAN GO BACKWORDS FOR A SINGLY LINKED LIST.
//
// ADVANTAGES/DISADVANTAGES ARRAY:
//	ADVANTAGE: ARRAYS LET YOU GET DIRECT ACCESS TO A CERTAIN ELEMENT AT THE INDEX WHICH MAKES IT VERY FAST TO GO THROUGH AND FIND A SPECIFIC ITEM.
//	DISADVANTAGE: THE SIZE OF THE ARRAY IS FIXED AND CANT BE CHANGED LATER IN THE CODE.
//
//
//
//
//
#include "Data.h"
#include "List.h"
#include "Node.h"
#include "menu.h"
int main()
{
	menu m;
	m.run_app();
	return 0;
}